name: wasm-curios
version: 0.1.0.0
github: "valmirjunior0088/wasm-curios"
license: BSD3
author: "Valmir Pretto"
maintainer: "valmirjunior0088 dot gmail dot com"
copyright: "(2022 - present) Valmir Pretto"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/valmirjunior0088/wasm-curios#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 1
- mtl >= 2.2 && < 3

default-extensions:
- NamedFieldPuns
- LambdaCase

library:
  source-dirs: src

executables:
  wasm-curios-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-curios

